#spring:
#  security:
#    user:
#      name: peter
#      password: codeone

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
    
---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/springpizza
    username: pizzauser
    password: pizzapassword
    
logging:
  level:
    tacos: WARN
    
